import { expect, it } from "vitest"
import { readFileSync } from "node:fs"

const bulk = readFileSync("wordpress/plugins/wholesalehub-supplier-lanes/includes/class-wholesalehub-bulk-order.php", "utf8")
const lane = readFileSync("wordpress/plugins/wholesalehub-supplier-lanes/wholesalehub-supplier-lanes.php", "utf8")
const exportPlugin = readFileSync("wordpress/plugins/avocadoss-supplier-order-export/includes/class-wholesalehub-supplier-order-export.php", "utf8")

it("keeps bulk data server-side and uses the WooCommerce checkout basket", () => {
  expect(bulk).toContain("MAX_BYTES = 10485760")
  expect(bulk).toContain("MAX_ROWS = 1000")
  expect(bulk).toContain("한 번에 최대 1,000행까지 주문할 수 있습니다. 파일을 나누어 업로드해 주세요.")
  expect(bulk).toContain("count($rows) > self::MAX_ROWS + 1")
  expect(bulk).toContain("if(!self::allowed())return $items")
  expect(bulk).toContain("if($key==='orders')$out['bulk-order']='엑셀 대량주문'")
  expect(bulk).toContain("엑셀로 여러 배송지를 한 번에 주문하세요")
  expect(bulk).toContain("대량주문 엑셀 양식 다운로드")
  expect(bulk).toContain("wh-bulk-upload")
  expect(bulk).toContain("사용방법")
  expect(bulk).toContain("도매허브_대량주문_양식_")
  expect(bulk).toContain("parent.post_status='publish'")
  expect(bulk).toContain("$v->is_purchasable()")
  expect(bulk).not.toContain("판매가(참고)")
  expect(bulk).toContain("wp_footer")
  expect(bulk).toContain("wh-bulk-home")
  expect(bulk).toContain("엑셀 대량주문 바로가기")
  expect(bulk).toContain("주문 상품 확인")
  expect(bulk).toContain("wp_check_filetype_and_ext")
  expect(bulk).toContain("hash_file('sha256'")
  expect(bulk).toContain("wholesalehub_bulk_shipments")
  expect(bulk).toContain("idempotency_key")
  expect(bulk).toContain("wholesalehub_bulk_rows")
  expect(bulk).toContain("shipping_snapshot")
  expect(bulk).toContain("mime_content_type")
  expect(bulk).toContain("expanded/$compressed>100")
  expect(bulk).toContain("ord($ref[0])-64<10")
  expect(bulk).toContain("['주문코드','상품명','옵션명','판매가'")
  expect(bulk).toContain("private static function order_code(int $variation):string{return 'H'.$variation;}")
  expect(bulk).toContain("offer_by_order_code")
  expect(bulk).toContain("주문코드를 확인하세요")
  expect(bulk).toContain("VLOOKUP")
  expect(bulk).toContain("autoFilter")
  expect(bulk).toContain("state=\"frozen\"")
  expect(bulk).toContain("입력예시")
  expect(bulk).toContain("_avo_approval_status")
  expect(bulk).toContain("woocommerce_account_menu_items")
  expect(bulk).toContain("woocommerce_email_order_meta_fields")
  expect(bulk).toContain("wh_bulk_result")
  expect(bulk).toContain("woocommerce_thankyou")
  expect(bulk).toContain("download_url('wh_bulk_result',$id,'xlsx')")
  expect(bulk).toContain("group_shipping")
  expect(bulk).toContain("actual_applied_amount")
  expect(bulk).toContain("wp_nonce_url")
  expect(bulk).toContain("flush_rewrite_rules(false)")
  expect(bulk).toContain("cart_data_from_offer")
  expect(bulk).toContain("wh-bulk-order-search")
  expect(bulk).toContain("customer_reference LIKE")
  expect(bulk).toContain("recipient LIKE")
  expect(bulk).toContain("manage_woocommerce")
  expect(bulk).toContain("WC()->cart->empty_cart()")
  expect(bulk).toContain("woocommerce_payment_complete")
})

it("exports each bulk item to its shipment recipient without supplier disclosure", () => {
  expect(exportPlugin).toContain("_wh_bulk_recipient")
  expect(exportPlugin).toContain("_wh_bulk_address1")
  expect(exportPlugin).toContain("$bulk_recipient ?: $recipient")
  expect(exportPlugin).not.toContain("supplier_name")
})

it("routes product purchase and cart access through checkout", () => {
  expect(lane).toContain("WC()->cart->empty_cart()")
  expect(lane).toContain("wc_get_checkout_url()")
  expect(lane).toContain("redirect_cart_to_checkout")
  expect(lane).not.toContain("장바구니 담기")
  expect(lane).toContain("is_checkout()")
})
